apiVersion: v1
kind: BuildConfig
metadata:
  name: php-ldap
spec:
  triggers:
    - type: Generic
      generic:
        secret: dd9709d12d8eb1ba
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/travisrogers05/php-ldap'
      ref: master
  strategy:
    type: Source
    dockerStrategy:
      noCache: true
      forcePull: true
  output:
    to:
      kind: ImageStreamTag
      name: 'php-ldap:1.0'
  resources: {}
  postCommit: {}
  nodeSelector: null